name: 'face-api-photobooth'

services:
  app:
    build: ./
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - 8084:8084
    restart: always

volumes:
  node_modules: